name: delivery
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  # แก้ไข syntax ของ sdk ให้ถูกต้อง
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloudinary_public: ^0.23.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  cloud_functions: ^6.0.2
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  image_picker: ^1.1.2
  firebase_storage: ^13.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  flutter_map_marker_cluster: ^1.3.6
  geocoding: ^2.1.1
  crypto: ^3.0.3
  
  # --- ส่วนที่ย้ายและเพิ่มเข้ามา ---
  http: ^1.2.1      # ย้ายมาจาก dev_dependencies
  http_parser: ^4.0.2 # ย้ายมาจาก dev_dependencies
  intl: ^0.19.0     # เพิ่มเข้ามาใหม่สำหรับจัดรูปแบบวันที่

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/